export default {
		productList: "/product/list",
		bannerList: "/banner/list",
		login: "/login",
		userInfo: "/user/info",
		addToShopcart: "/shopcart/add",
		shopcartList: "/shopcart/list",
		updateShopcart: "/shopcart/update",
		clearShopcart: "/shopcart/deleteByUser",
		batchDeleteShopcart: "/shopcart/batchDelete",
		areaList: "/position/area/",
		cityList: "/position/city/",
		provinceList: "/position/province/",
		addressList:"/user/addressList",
		addAddress:"/user/saveAddress",
		updateAddress:"/user/updateAddress",
		deleteAddress:"/user/deleteAddressById",
		getAddressById:"/user/address/",
		getOrderList:"/order/list",
		addOrder:"/order/save",
		updateOrder:"/order/updateOrder",
		updateOrderStatus:"/order/updateStatus",
	}
